# Generated by Django 2.1.7 on 2019-06-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190607_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_register',
            field=models.BooleanField(default=False),
        ),
    ]
