# Generated by Django 2.1.7 on 2019-06-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190609_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.CharField(default=1, max_length=212),
            preserve_default=False,
        ),
    ]
